# Generated by Django 3.1.5 on 2021-01-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
